title: libyt Documents (Dev)
description: libyt documents, this site is mainly for developing.
theme: just-the-docs

url: https://cindytsai.github.io/libyt/

# Aux links for the upper right navigation, create new tab once click
aux_links:
  cindytsai/libyt (dev): https://github.com/cindytsai/libyt
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
heading_anchors: true

# For copy button on code
enable_copy_code_button: true

# Callout configuration:
#   Info:
#   Notes:
#   Warning:
callouts:
  info:
    title: Information
    color: blue
  notes:
    title: Notes
    color: green
  warning:
    title: Warning
    color: yellow

# plugins
plugins:
  - jemoji