title: libyt Documents (Dev)
description: libyt documents, this site is mainly for developing.
theme: just-the-docs

url: https://cindytsai.github.io/libyt/

aux_links:
  cindytsai/libyt (dev): https://github.com/cindytsai/libyt
