# Test: If project can build successfully with different version of Python.

name: build-test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Job name: "build with python38"
  build-with-python38:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup Python environment
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      
      - name: Install yt
        run: |
          git clone --depth 1 -b libyt --single-branch "https://github.com/cindytsai/yt.git" "../yt"
          cd ../yt
          echo On cindytsai/yt branch $(git branch)
          pip install .
          
