# Test: 1. If project can build successfully with different version of Python or not.
#       2. Can the example run in serial and in parallel. Are the results the same?

name: build-test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Job name: "build with python38"
  build-with-python38:
    runs-on: ubuntu-latest
    steps:
      # Setup Python environment
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
          
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
          
      - name: Setup MPI environment
        run: sudo apt install -y openmpi-bin libopenmpi-dev

      - name: Install yt and mpi4py
        run: |
          git clone --depth 1 -b libyt --single-branch "https://github.com/cindytsai/yt.git" "../yt"
          cd ../yt
          git checkout libyt
          pip install .
          pip install mpi4py
          
      - name: Set PYTHON_PATH, NUMPY_PATH, MPI_PATH 
        run: |
          PYTHON_BIN=$(which python)
          PYTHON_PATH=${PYTHON_BIN%/*}
          cd $PYTHON_PATH/
          cd ..
          echo "PYTHON_PATH=$(pwd)" >> $GITHUB_ENV
          cd lib/python3.8/site-packages/numpy
          echo "NUMPY_PATH=$(pwd)" >> $GITHUB_ENV
          echo "MPI_PATH=/usr" >> $GITHUB_ENV
          
      - name: Read Python PATH
        run: echo "${{ env.PYTHON_PATH }}"
          
      - name: Read NumPy PATH
        run: echo "${{ env.NUMPY_PATH }}"
        
      - name: Read MPI PATH
        run: echo "${{ env.MPI_PATH }}"
      
      - name: Build libyt
        run: |
          cd $GITHUB_WORKSPACE/src
          sed -i 's@$(YOUR_PYTHON_PATH)@"${{ env.PYTHON_PATH }}"@' Makefile
          sed -i 's@$(YOUR_NUMPY_PATH)@"${{ env.NUMPY_PATH }}"@' Makefile
          sed -i 's@$(YOUR_MPI_PATH)@"${{ env.MPI_PATH }}"@' Makefile
          make clean
          make
          
