# Test: 1. If project can build successfully with different version of Python or not.
#       2. Can the example run in serial and in parallel. Are the results the same?

name: build-test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Job name: "build with python38"
  build-with-python38:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
      
      # Setup Python environment
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      
#       - name: Install yt
#         run: |
#           git clone --depth 1 -b libyt --single-branch "https://github.com/cindytsai/yt.git" "../yt"
#           cd ../yt
#           git checkout libyt
#           pip install .
          
      - name: Set Python PATH
        run: |
          PYTHON_BIN=$(which python)
          PYTHON_PATH=${PYTHON_BIN%/*}
          cd $PYTHON_PATH/
          cd ..
          echo "PYTHON_PATH=$(pwd)" >> $GITHUB_ENV
          
      - name: Read Python PATH
        run: |
          echo "${{ env.PYTHON_PATH }}"
          
      - name: Build libyt
        run: echo $GITHUB_ACTION_REPOSITORY
      
          
