# Test if it can run on multiplatform and both in serial (gcc) and parallel (openmpi)

name: CMake Build Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - '**.md'
  workflow_dispatch:

jobs:
  cmake-build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout libyt repo
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/.github/tools/requirements.txt

      - name: Setup MPI environment
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: 'openmpi'

      - name: Install yt, mpi4py, and yt_libyt
        run: |
          pip install mpi4py yt
          cd $GITHUB_WORKSPACE
          cd ..
          git clone --depth 1 -b libyt-dev --single-branch "https://github.com/cindytsai/yt_libyt.git" yt_libyt
          cd yt_libyt
          pip install .

      - name: Update GitHub Environment Variables
        run: |
          echo "PYTHON_PATH=${{ env.pythonLocation }}" >> $GITHUB_ENV
          echo "MPI_PATH=/usr" >> $GITHUB_ENV
          echo "LIBYT_PARALLEL_INSTALL_PATH=$GITHUB_WORKSPACE/libyt_parallel" >> $GITHUB_ENV
          echo "LIBYT_SERIAL_INSTALL_PATH=$GITHUB_WORKSPACE/libyt_serial" >> $GITHUB_ENV

      - name: Build libyt -- Parallel (MPI)
        run: | 
          cd $GITHUB_WORKSPACE
          rm -rf build
          cmake -B build -S . 
                -DMPI_PATH="${{ env.MPI_PATH }}"
                -DPYTHON_PATH="${{ env.PYTHON_PATH }}"
                -DCMAKE_INSTALL_PREFIX="${{ env.LIBYT_PARALLEL_INSTALL_PATH }}"
          cmake --build build
          cmake --install build

      - name: Build libyt -- Serial (GCC)
        run: | 
          cd $GITHUB_WORKSPACE
          rm -rf build-serial
          cmake -B build-serial -S . 
                -DSERIAL_MODE:BOOL=ON
                -DPYTHON_PATH="${{ env.PYTHON_PATH }}"
                -DCMAKE_INSTALL_PREFIX="${{ env.LIBYT_SERIAL_INSTALL_PATH }}"
          cmake --build build-serial
          cmake --install build-serial

      - name: Prepare Test
        run: |
          cd $GITHUB_WORKSPACE/example
          cp $GITHUB_WORKSPACE/.github/tests/test-DataIO/DataIOTest.py .
          sed -i 's/inline_script/DataIOTest/' example.cpp

      - name: Generate Density Data for Testing
        run: |
          cd $GITHUB_WORKSPACE/example
          cp $GITHUB_WORKSPACE/.github/tools/generate_density_data.cpp .
          g++ -o generate_density_data generate_density_data.cpp
          ./generate_density_data

      - name: Test Run and DataIO Test - example - Serial
        run: |
          cd $GITHUB_WORKSPACE/example
          make clean
          make OPTIONS=-DSERIAL_MODE LIBYT_PATH="${{ env.LIBYT_SERIAL_INSTALL_PATH }}"
          ./example

      - name: Test Run and DataIO Test - example - Parallel (MPI 3)
        run: |
          cd $GITHUB_WORKSPACE/example
          make clean
          make LIBYT_PATH="${{ env.LIBYT_PARALLEL_INSTALL_PATH }}" MPI_PATH="${{ env.MPI_PATH }}"
          OMPI_MCA_osc=sm,pt2pt mpirun -np 3 ./example
