name: Unit Testing

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'
      - '**.md'
  workflow_dispatch:

jobs:
  # TODO: need also serial test
  mpi-unit-test:
    name: Unit Test (MPI)
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        mpi_compiler: ['openmpi', 'mpich']
        python_version: ['3.10']
        build_options: ["-DINTERACTIVE_MODE=ON -DLIBYT_RUN_TEST=ON -DUSE_PYBIND11=ON", "-DINTERACTIVE_MODE=ON -DLIBYT_RUN_TEST=ON -DUSE_PYBIND11=OFF"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python_version }} environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Setup MPI ${{ matrix.mpi_compiler }} environment
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi_compiler }}

      - name: Install other dependencies
        run: |
          sudo apt-get install -y libreadline-dev

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=build-unittest-mpi" >> "$GITHUB_OUTPUT"

      - name: Configure CMake (${{ matrix.build_options }})
        run: |
          cd ${{ github.workspace }}
          rm -rf ${{ steps.strings.outputs.build-output-dir }}
          cmake ${{ matrix.build_options }} -B ${{ steps.strings.outputs.build-output-dir }} -S .

      - name: Build
        run: |
          cd ${{ github.workspace }}
          cmake --build ${{ steps.strings.outputs.build-output-dir }}

      - name: Run tests (MPI and RMA)
        working-directory: ${{ steps.strings.outputs.build-output-dir }}/test
        run: |
          OMPI_MCA_osc=sm,pt2pt mpirun -np 3 ./TestCommMPI --colorful

      - name: Run tests (PythonShell - MPI)
        working-directory: ${{ steps.strings.outputs.build-output-dir }}/test
        run: |
          OMPI_MCA_osc=sm,pt2pt mpirun -np 3 ./TestPythonShellWithCommMPI --colorful
          
      - name: Run tests (DataStructure - MPI)
        working-directory: ${{ steps.strings.outputs.build-output-dir }}/test
        run: |
          OMPI_MCA_osc=sm,pt2pt mpirun -np 3 ./TestDataStructureAmrWithCommMpi --colorful
